/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kairuisam
 */
public class Frame_Comfirm extends javax.swing.JFrame implements Interface_Assign
{

    public ArrayList<Data_Maintenance> maintance_data = new ArrayList<>(); 
    String filePath =  "TXT_DATA/sam_love.txt";
    String file_of_Staff_Path = "TXT_DATA/scheduler.txt";
    Class_Function_Assign Function = new Class_Function_Assign();
    public ArrayList<String> Arread_staff_data = new ArrayList<>(); 
    String target_ID;
    String newValue;
    
     //------------------------------------------------------------------------------------
    
    @Override
    public void addDataToComboBox(Data_Maintenance maintance_data) {}
   
    //------------------------------------------------------------------------------------
    
    public Frame_Comfirm(String assignID) throws IOException 
    {
        initComponents();
        Function.read_file_data(filePath, maintance_data);
        Function.read_staff_data(file_of_Staff_Path, Arread_staff_data, CB_S_ID);
        Label_ID.setText(assignID);
        target_ID = assignID;
    }

    //------------------------------------------------------------------------------------
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CB_S_ID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Label_ID = new javax.swing.JLabel();
        Btn_Assign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Assgn Staff For Specific Issues");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 360, 100));

        CB_S_ID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CB_S_ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jPanel1.add(CB_S_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 308, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("STAFF  ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("ISSUSE  ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        Label_ID.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel1.add(Label_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, 40));

        Btn_Assign.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Btn_Assign.setText("Assign");
        Btn_Assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AssignActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AssignActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
            "Are you sure to assign?",
            "Confirm",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION)
        {
            try
            {
                newValue = (String)CB_S_ID.getSelectedItem();
                Function.updateFileData(filePath, target_ID, newValue, maintance_data);
                Function.Change_Frame(this,new Frame_Maintenance_Operation());
            }
            catch (IOException ex)
            {
                Logger.getLogger(Frame_Assign_Staff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_Btn_AssignActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Assign;
    private javax.swing.JComboBox<String> CB_S_ID;
    private javax.swing.JLabel Label_ID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
