package scheduler;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.io.*;
import java.awt.Dimension;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yeo yu le
 */
public class Hall_Availability_Operation extends javax.swing.JFrame {

    /**
     * Creates new form Hall_Availability_Operation
     */
    private int position;
    ArrayList<Schedule> schedule;
    private EditListener listener;
    private DataValidation validater;
    
    public Hall_Availability_Operation() {
        initComponents();
    }

    public Hall_Availability_Operation(int position, EditListener listener){
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);        
        this.position = position;
        this.listener = listener;

        try{
            schedule = FileOperation.ReadSchedule("Schedule.txt");
            Schedule scheduleData = schedule.get(position);
            cboScheduleType.setSelectedItem(scheduleData.getSchedule_Type());
            txtHallName.setText(scheduleData.getHall_Name());
            SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
            try{
                dteStart.setDate(dformat.parse(scheduleData.getStart_Date()));
                dteEnd.setDate(dformat.parse(scheduleData.getEnd_Date()));
            }catch (ParseException px){System.out.println(px);}
            String[] timePart1 = scheduleData.getStart_Time().replace("AM", "").replace("PM", "").split(":");
            String[] timePart2 = scheduleData.getEnd_Time().replace("AM", "").replace("PM", "").split(":");
            
            cboStartHour.setSelectedItem(timePart1[0]);
            cboEndHour.setSelectedItem(timePart2[0]);
            
            spnStartMinutes.setValue(Integer.parseInt(timePart1[1]));
            spnEndMinutes.setValue(Integer.parseInt(timePart2[1]));
            String remark;

            if (( remark= scheduleData.getRemarks()).equals("null")){
                txtfRemarks.setText(null);
            }
            else{
                txtfRemarks.setText(remark);
            }
            
        } catch(IOException ex){System.out.println(ex);}
    }

    public void windowClosing(){
        if (listener != null){
            listener.EditView();
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cboScheduleType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        pnlStart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dteStart = new com.toedter.calendar.JDateChooser();
        cboStartHour = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        spnStartMinutes = new javax.swing.JSpinner();
        txtAmPm1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dteEnd = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cboEndHour = new javax.swing.JComboBox<>();
        spnEndMinutes = new javax.swing.JSpinner();
        txtAmPm2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfRemarks = new javax.swing.JTextArea();
        lblRemark = new javax.swing.JLabel();
        txtHallName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setText("Schedule Type");

        cboScheduleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Availability Slot", "Maintenance", "Reserved" }));
        cboScheduleType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboScheduleTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("Hall Name");

        pnlStart.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Start Date & Time"));

        jLabel1.setText("Start Date");

        dteStart.setDateFormatString("dd-MM-yyyy");

        cboStartHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "1", "2", "3", "4", "5", "6" }));
        cboStartHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboStartHourActionPerformed(evt);
            }
        });

        jLabel2.setText("Start Time");

        spnStartMinutes.setModel(new javax.swing.SpinnerNumberModel(00, 00,59 , 1)
        );
        spnStartMinutes.setEditor(new javax.swing.JSpinner.NumberEditor(spnStartMinutes, "00"));

        txtAmPm1.setEditable(false);

        jLabel4.setText("End Date");

        dteEnd.setDateFormatString("dd-MM-yyyy");

        jLabel5.setText("End Time");

        cboEndHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "1", "2", "3", "4", "5", "6" }));
        cboEndHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEndHourActionPerformed(evt);
            }
        });

        spnEndMinutes.setModel(new javax.swing.SpinnerNumberModel(00, 00,59 , 1)
        );
        spnEndMinutes.setEditor(new javax.swing.JSpinner.NumberEditor(spnEndMinutes, "00"));

        txtAmPm2.setEditable(false);

        javax.swing.GroupLayout pnlStartLayout = new javax.swing.GroupLayout(pnlStart);
        pnlStart.setLayout(pnlStartLayout);
        pnlStartLayout.setHorizontalGroup(
            pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStartLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStartLayout.createSequentialGroup()
                        .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlStartLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cboStartHour, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnStartMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAmPm1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlStartLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(dteStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(dteEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStartLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(cboEndHour, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnEndMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmPm2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlStartLayout.setVerticalGroup(
            pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dteStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(dteEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnStartMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmPm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboStartHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spnEndMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmPm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEndHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        txtfRemarks.setColumns(20);
        txtfRemarks.setRows(5);
        jScrollPane1.setViewportView(txtfRemarks);

        lblRemark.setText("Remarks");

        txtHallName.setEnabled(false);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRemark)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 361, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(txtHallName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel8)
                    .addGap(18, 18, 18)
                    .addComponent(cboScheduleType, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(402, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHallName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(57, 57, 57)
                .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblRemark)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cboScheduleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(495, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboScheduleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboScheduleTypeActionPerformed
        txtfRemarks.setText(null);
        if (cboScheduleType.getSelectedItem().toString().equals("Availability Slot")){
            txtfRemarks.setVisible(false);
        }
        else{
            txtfRemarks.setVisible(true);
        }
    }//GEN-LAST:event_cboScheduleTypeActionPerformed

    private void cboStartHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboStartHourActionPerformed
        Schedule s = new Schedule();
        s.showTime(cboStartHour, txtAmPm1);
    }//GEN-LAST:event_cboStartHourActionPerformed

    private void cboEndHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEndHourActionPerformed
        Schedule s = new Schedule();
        s.showTime(cboEndHour, txtAmPm2);
    }//GEN-LAST:event_cboEndHourActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String type = cboScheduleType.getSelectedItem().toString();
        
        String hallName = txtHallName.getText();
        
        String start_hour = cboStartHour.getSelectedItem().toString();
        String start_minutes = String.format("%02d",spnStartMinutes.getValue());
        String time1 = txtAmPm1.getText();
        
        String end_hour = cboEndHour.getSelectedItem().toString();
        String end_minutes = String.format("%02d", spnEndMinutes.getValue());
        String time2 = txtAmPm2.getText();
        
        String start_time = start_hour + ":" + start_minutes + time1;
        String end_time = end_hour + ":" + end_minutes + time2;

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String start_date = dateFormat.format(dteStart.getDate());
        String end_date = dateFormat.format(dteEnd.getDate());
        String remark = txtfRemarks.getText();
        if (remark.equals("")){remark = null;}
        

        validater = new Schedule(type,hallName,start_date,start_time,end_date,end_time,remark,position);
        
        if (validater.ValidateData()){
            Schedule editedRow = schedule.get(position);
            
            editedRow.setSchedule_Type(type);
            editedRow.setHall_Name(hallName);
            editedRow.setStart_Date(start_date);
            editedRow.setStart_Time(start_time);
            editedRow.setEnd_Date(end_date);
            editedRow.setEnd_Time(end_time);
            editedRow.setRemarks(remark);
            
            FileOperation.FileWriting("Schedule.txt", schedule);
            JOptionPane.showMessageDialog(null, "Data edited successfully");
            this.dispose();
            windowClosing();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "You are going to delete the data. Do you confirm?", "Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION){        
            FileOperation.DeleteFile("Schedule.txt");
            schedule.remove(schedule.get(position));

            for (Schedule sc: schedule){
                Schedule s = new Schedule(sc.getSchedule_Type(),sc.getHall_Name(),sc.getStart_Date(),sc.getStart_Time(),sc.getEnd_Date(),sc.getEnd_Time(),sc.getRemarks());
                s.WriteSchedule();
            }
            JOptionPane.showMessageDialog(null, "The data has been deleted successfully");
            this.dispose();
            windowClosing();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hall_Availability_Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hall_Availability_Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hall_Availability_Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hall_Availability_Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hall_Availability_Operation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cboEndHour;
    private javax.swing.JComboBox<String> cboScheduleType;
    private javax.swing.JComboBox<String> cboStartHour;
    private com.toedter.calendar.JDateChooser dteEnd;
    private com.toedter.calendar.JDateChooser dteStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRemark;
    private javax.swing.JPanel pnlStart;
    private javax.swing.JSpinner spnEndMinutes;
    private javax.swing.JSpinner spnStartMinutes;
    private javax.swing.JTextField txtAmPm1;
    private javax.swing.JTextField txtAmPm2;
    private javax.swing.JTextField txtHallName;
    private javax.swing.JTextArea txtfRemarks;
    // End of variables declaration//GEN-END:variables
}
