package scheduler;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yeo yu le
 */
import admin.User;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.*;
import java.awt.image.BufferedImage;
import manager.Data_Maintenance;
import java.util.ArrayList;

import java.io.IOException;
public class Scheduler_Home extends javax.swing.JFrame{

    private SetImage imageSetter = new ImageSetter();
    private User currentUser = User.getLoggedInUser();
    private ArrayList<Data_Maintenance> maintenance;

    public Scheduler_Home() {        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        System.out.println("Current User: " + currentUser); // Check if this is null
        User.setProfile( lblProfilePic, currentUser);
        imageSetter.SetImageSize(lblHall1,lblSchedule1,lblView12);
        lblHall1.setText("<html>&nbsp;&nbsp;Hall<br>Manager</html>");
        lblView12.setText("<html>View<br>Task</html>");
        try{
            FileOperation file = new FileOperation();
            maintenance = file.ReadMaintenance("issue.txt");
            int count = 0;
            for (Data_Maintenance d: maintenance){
                    count++;
            }
            lblPending.setText(Integer.toString(count));
        } catch(IOException ex){}   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNav = new javax.swing.JPanel();
        lblProfilePic = new javax.swing.JLabel();
        lblView12 = new javax.swing.JLabel();
        lblSchedule1 = new javax.swing.JLabel();
        lblHall1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPending = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblStartHallManagement = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblStartScheduling = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNav.setBackground(new java.awt.Color(37, 5, 62));

        lblProfilePic.setText("jLabel4");

        lblView12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblView12.setForeground(new java.awt.Color(255, 255, 255));
        lblView12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/ViewTask.png"))); // NOI18N
        lblView12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblView12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblView12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblView12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblView12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblView12MouseExited(evt);
            }
        });

        lblSchedule1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblSchedule1.setForeground(new java.awt.Color(255, 255, 255));
        lblSchedule1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchedule1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/schedule_icon.png"))); // NOI18N
        lblSchedule1.setText("Schedule");
        lblSchedule1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSchedule1.setMaximumSize(new java.awt.Dimension(62, 60));
        lblSchedule1.setMinimumSize(new java.awt.Dimension(62, 60));
        lblSchedule1.setPreferredSize(new java.awt.Dimension(62, 60));
        lblSchedule1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSchedule1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSchedule1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSchedule1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSchedule1MouseExited(evt);
            }
        });

        lblHall1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblHall1.setForeground(new java.awt.Color(255, 255, 255));
        lblHall1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHall1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/icons8-hall-96.png"))); // NOI18N
        lblHall1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHall1.setPreferredSize(new java.awt.Dimension(69, 48));
        lblHall1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblHall1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHall1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHall1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHall1MouseExited(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(89, 14, 147));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavLayout = new javax.swing.GroupLayout(pnlNav);
        pnlNav.setLayout(pnlNavLayout);
        pnlNavLayout.setHorizontalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addGroup(pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNavLayout.createSequentialGroup()
                        .addGroup(pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNavLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblProfilePic))
                            .addGroup(pnlNavLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHall1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblView12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlNavLayout.setVerticalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblProfilePic)
                .addGap(87, 87, 87)
                .addComponent(lblHall1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblSchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblView12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pending Jobs");

        lblPending.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPending.setForeground(new java.awt.Color(102, 102, 255));
        lblPending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPendingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPendingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPending)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(lblPending)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Start Hall Mangement");

        lblStartHallManagement.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblStartHallManagement.setForeground(new java.awt.Color(102, 102, 255));
        lblStartHallManagement.setText("Let's start");
        lblStartHallManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStartHallManagementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStartHallManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStartHallManagementMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartHallManagement)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStartHallManagement)
                .addGap(23, 23, 23))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Today's Happening");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DASHBOARD");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Scheduling Now");

        lblStartScheduling.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblStartScheduling.setForeground(new java.awt.Color(102, 102, 255));
        lblStartScheduling.setText("GO GO GO");
        lblStartScheduling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStartSchedulingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStartSchedulingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStartSchedulingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartScheduling)
                    .addComponent(jLabel5))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblStartScheduling)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblView12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblView12MouseClicked
        View_Task view = new View_Task();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblView12MouseClicked

    private void lblView12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblView12MouseEntered
        ImageSetter.SetLabelMouseEnter(lblView12);
    }//GEN-LAST:event_lblView12MouseEntered

    private void lblView12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblView12MouseExited
        ImageSetter.SetLabelMouseExit(lblView12, pnlNav);
    }//GEN-LAST:event_lblView12MouseExited

    private void lblSchedule1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSchedule1MouseClicked
        Hall_Availability hall = new Hall_Availability();
        hall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSchedule1MouseClicked

    private void lblSchedule1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSchedule1MouseEntered
        ImageSetter.SetLabelMouseEnter(lblSchedule1);
    }//GEN-LAST:event_lblSchedule1MouseEntered

    private void lblSchedule1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSchedule1MouseExited
        ImageSetter.SetLabelMouseExit(lblSchedule1, pnlNav);
    }//GEN-LAST:event_lblSchedule1MouseExited

    private void lblHall1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHall1MouseClicked
        Hall_Manager hall = new Hall_Manager();
        hall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblHall1MouseClicked

    private void lblStartHallManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartHallManagementMouseEntered
        lblStartHallManagement.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblStartHallManagementMouseEntered

    private void lblStartHallManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartHallManagementMouseExited
        lblStartHallManagement.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_lblStartHallManagementMouseExited

    private void lblStartSchedulingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartSchedulingMouseEntered
        lblStartScheduling.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblStartSchedulingMouseEntered

    private void lblStartSchedulingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartSchedulingMouseExited
        lblStartScheduling.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_lblStartSchedulingMouseExited

    private void lblStartHallManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartHallManagementMouseClicked
        Hall_Manager hall = new Hall_Manager();
        hall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblStartHallManagementMouseClicked

    private void lblStartSchedulingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartSchedulingMouseClicked
        Hall_Availability hall = new Hall_Availability();
        hall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblStartSchedulingMouseClicked

    private void lblPendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingMouseEntered
        lblPending.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblPendingMouseEntered

    private void lblPendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingMouseExited
        lblPending.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_lblPendingMouseExited

    private void lblHall1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHall1MouseEntered
        ImageSetter.SetLabelMouseEnter(lblHall1);
    }//GEN-LAST:event_lblHall1MouseEntered

    private void lblHall1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHall1MouseExited
        ImageSetter.SetLabelMouseExit(lblHall1, pnlNav);
    }//GEN-LAST:event_lblHall1MouseExited

    private void lblPendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingMouseClicked
        View_Task view = new View_Task();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPendingMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        currentUser.logout();
        System.out.println(currentUser);
        System.out.println(User.getLoggedInUser());
        System.out.println("Successfully Logged out.");
        this.dispose();
        admin.Frame_Login login = new admin.Frame_Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scheduler_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scheduler_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scheduler_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scheduler_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scheduler_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblHall1;
    private javax.swing.JLabel lblPending;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblSchedule1;
    private javax.swing.JLabel lblStartHallManagement;
    private javax.swing.JLabel lblStartScheduling;
    private javax.swing.JLabel lblView12;
    private javax.swing.JPanel pnlNav;
    // End of variables declaration//GEN-END:variables
}
